server guard

diff --git a/server_manager/jobs/updater b/server_manager/jobs/updater
--- a/server_manager/jobs/updater
+++ b/server_manager/jobs/updater
@@ -225,8 +225,9 @@ download_enshrouded() {
   export STEAM_COMPAT_CLIENT_INSTALL_PATH="/home/enshrouded/.steam/steam"
   export STEAM_COMPAT_DATA_PATH="$install_path/steamapps/compatdata/$steam_app_id"
   export STEAM_DIR="/home/enshrouded/.steam/steam/"
+  [[ -x "${STEAMCMD_BIN:-}" ]] || fatal "Missing steamcmd binary: ${STEAMCMD_BIN:-<unset>}"
 
-  "$steamcmd_path" +@sSteamCmdForcePlatformType windows +force_install_dir "$install_path" +login anonymous +app_update "$steam_app_id" "$GAME_BRANCH $STEAMCMD_ARGS" +quit
+  "$STEAMCMD_BIN" +@sSteamCmdForcePlatformType windows +force_install_dir "$install_path" +login anonymous +app_update "$steam_app_id" "$GAME_BRANCH $STEAMCMD_ARGS" +quit
 }
 
 check_for_updates() {
